apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-celery-four
  namespace: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-celery-four
  template:
    metadata:
      labels:
        app: demo-celery-four
    spec:
      containers:
      - name: demo-celery-four
        image: 961328178101.dkr.ecr.ap-south-1.amazonaws.com/rounds-api-test:celery-v0.0.1
        imagePullPolicy: IfNotPresent
