apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-imgq-simck
  namespace: celery
  labels:
    app: celery-imgq-simck
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: celery-imgq-simck
  template:
    metadata:
      labels:
        app: celery-imgq-simck
    spec:
      serviceAccountName : celery
      containers:
      - name: celery-imgq-simck # Name of the container
        image: 961328178101.dkr.ecr.ap-south-1.amazonaws.com/rounds-api:v8.6.3
        imagePullPolicy: IfNotPresent
        env:
        - name: ROUNDS_ENABLE_CELERY
          value: enabled
        - name: ROUNDS_ENV # For Secrets Manager
          value: dev
        - name: GRAYLOG_HOST
          value: "10.0.1.40"
        - name: GRAYLOG_PORT
          value: "12201"
        command: ["/bin/sh","-c"]
        args: ["cp /settings/local_settings.py /app/kernel/local_settings.py && celery  --app=runcelery worker -Q IMGQ,SIMCK --loglevel=info -P gevent --autoscale=5,2 "]
        resources:
          requests:
            memory: "700M"
            cpu: "300m"
          limits:
            memory: "1G"
            cpu: "350m"
        volumeMounts:
        - name: celery-imgq-simck-local-settings
          mountPath: /settings
          readOnly: true
        - name: key1
          mountPath: /etc/ssh-key1
        - name: key2
          mountPath: /etc/ssh-key2
        - name: key3
          mountPath: /video-zip-pg
      nodeSelector:
        workload: marrow-api
      volumes:
      - name: celery-imgq-simck-local-settings
        configMap:
          name: celery-local-settings
      - name: key1
        secret:
          secretName: 3176b6db91af79067cbb902a90bdffd3
      - name: key2
        secret:
          secretName: pk
      - name: key3
        secret:
          secretName: pk-pg