apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-aspq-ns-ccemail-vault
  namespace: celery
  labels:
    app: celery-aspq-ns-ccemail-vault
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: celery-aspq-ns-ccemail-vault
  template:
    metadata:
      labels:
        app: celery-aspq-ns-ccemail-vault
    spec:
      containers:
      - name: celery-aspq-ns-ccemail-vault # Name of the container
        image: 961328178101.dkr.ecr.ap-south-1.amazonaws.com/rounds-api:v8.6.3
        imagePullPolicy: IfNotPresent
        env:
        - name: ROUNDS_ENABLE_CELERY
          value: enabled
        - name: ROUNDS_ENV # For Secrets Manager
          value: dev
        - name: GRAYLOG_HOST
          value: "10.0.1.40"
        - name: GRAYLOG_PORT
          value: "12201"
        # command: ["sleep","10000"]
        command: ["/bin/sh","-c"]
        args: ["cp /settings/local_settings.py /app/kernel/local_settings.py && celery --app=runcelery worker -Q ASPQ,CC_EMAIL,NS,RTLMT,EXCP --loglevel=info -P gevent --autoscale=5,2"]
        ports:
        - containerPort: 8000 # Port that the container expose
        resources:
          requests:
            memory: "1500M"
            cpu: "800m"
          limits:
            memory: "1500M"
            cpu: "800m"
        volumeMounts:
        - name: celery-aspq-ns-ccemail-vault-excp-local-settings
          mountPath: /settings
          readOnly: true
        - name: key1
          mountPath: /etc/ssh-key1
        - name: key2
          mountPath: /etc/ssh-key2
      nodeSelector:
        workload: marrow-api
      volumes:
      - name: celery-aspq-ns-ccemail-vault-excp-local-settings
        configMap:
          name: celery-local-settings
      - name: key1
        secret:
          secretName: 3176b6db91af79067cbb902a90bdffd3
      - name: key2
        secret:
          secretName: pk
