apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-one
  namespace: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api-one
  template:
    metadata:
      labels:
        app: demo-api-one
    spec:
      containers:
      - name: demo-api-one
        image: 961328178101.dkr.ecr.ap-south-1.amazonaws.com/rounds-api-test:v0.0.1
        imagePullPolicy: IfNotPresent
