apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpublished-app
  namespace: internal
  labels:
    app: unpublished-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: unpublished-app
  template:
    metadata:
      labels:
        app: unpublished-app
    spec:
      serviceAccountName : api-role-internal
      containers:
      - name: rounds-api # Name of the container
        image: 961328178101.dkr.ecr.ap-south-1.amazonaws.com/rounds-api:v8.6.3
        imagePullPolicy: IfNotPresent
        env:
        - name: ROUNDS_ENABLE_APPS
          value: kaizen
        - name: ROUNDS_ENV # For Secrets Manager
          value: production
        - name: AWS_SM_NAME
          value: prod/app-secrets/p0
        - name: GRAYLOG_HOST
          value: "10.0.1.40"
        - name: GRAYLOG_PORT
          value: "12201"
        # command: ["sleep","10000"]
        command: ["/bin/sh","-c"]
        args: ["cp /settings/local_settings.py /app/kernel/local_settings.py && python3 runserver.py"]
        ports:
        - containerPort: 8000 # Port that the container expose
        resources:
          requests:
            memory: "200M"
            cpu: "100m"
          limits:
            memory: "500M"
            cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: unpublished-local-settings
          mountPath: /settings
          readOnly: true
        - name: key1
          mountPath: /etc/ssh-key1
        - name: key2
          mountPath: /etc/ssh-key2
        - name: key3
          mountPath: /license-key-sign
        - name: gcprecaptcha
          mountPath: /googlesa
      nodeSelector:
        workload: dr-api
      volumes:
      - name: unpublished-local-settings
        configMap:
          name: unpublished-local-settings
      - name: key1
        secret:
          secretName: 3176b6db91af79067cbb902a90bdffd3
      - name: key2
        secret:
          secretName: pk
      - name: key3
        secret:
          secretName: a998e3eed679726bd54c0012c769943d
      - name: gcprecaptcha
        secret:
          secretName: googlesa
