name: Test Environment Approval

on:
  push:
    branches: [ main ]

jobs:
  Plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is before approval"
      - run: echo "Hellow marrow"
      - run: echo "Terraform plan"
    environment:
      name: Test-stage
  Apply:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is After approval"
      - run: echo "Bye marrow"
      - run: echo "Terraform apply"

