name: Test Environment Approval

on:
push:
branches:
- main

jobs:
test-environment:
runs-on: ubuntu-latest

```
environment:
  name: Test-staging

steps:
  - name: Print message
    run: echo "If you see this, the environment approval was granted!"
```
